param(
    [string]$FxcPath,
    [switch]$Verify
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$shaderPath = Join-Path $repoRoot 'SexyAppFramework\shaders\Fsr1Pass.hlsl'
$includePath = Join-Path $repoRoot 'third_party\FidelityFX-FSR'
$headerPath = Join-Path $repoRoot 'SexyAppFramework\shaders\Fsr1Shaders.generated.h'

if (-not $FxcPath) {
    $preferred = 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64\fxc.exe'
    if (Test-Path -LiteralPath $preferred) {
        $FxcPath = $preferred
    } else {
        $FxcPath = Get-ChildItem 'C:\Program Files (x86)\Windows Kits\10\bin' -Filter fxc.exe -Recurse |
            Where-Object { $_.DirectoryName -like '*\x64' } |
            Sort-Object FullName -Descending |
            Select-Object -First 1 -ExpandProperty FullName
    }
}

if (-not $FxcPath -or -not (Test-Path -LiteralPath $FxcPath)) {
    throw 'fxc.exe was not found. Pass -FxcPath from Windows SDK 10.0.26100.0 for the checked-in bytecode.'
}

$tempRoot = Join-Path ([IO.Path]::GetTempPath()) ('pvz-fsr1-' + [Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $tempRoot | Out-Null

try {
    $easuPath = Join-Path $tempRoot 'Fsr1Easu.cso'
    $rcasPath = Join-Path $tempRoot 'Fsr1Rcas.cso'
    $commonArgs = @(
        '/nologo', '/T', 'cs_5_0', '/E', 'mainCS', '/O3', '/Ges', '/WX',
        '/Qstrip_debug', '/Qstrip_reflect', '/I', $includePath
    )

    & $FxcPath @commonArgs /D FSR_PASS_EASU=1 /Fo $easuPath $shaderPath
    if ($LASTEXITCODE -ne 0) { throw "EASU compilation failed with exit code $LASTEXITCODE." }

    & $FxcPath @commonArgs /D FSR_PASS_RCAS=1 /Fo $rcasPath $shaderPath
    if ($LASTEXITCODE -ne 0) { throw "RCAS compilation failed with exit code $LASTEXITCODE." }

    function Format-ByteArray([string]$path, [string]$name) {
        $bytes = [IO.File]::ReadAllBytes($path)
        $lines = [Collections.Generic.List[string]]::new()
        $lines.Add("inline constexpr unsigned char $name" + '[] = {')
        for ($offset = 0; $offset -lt $bytes.Length; $offset += 12) {
            $end = [Math]::Min($offset + 11, $bytes.Length - 1)
            $values = for ($index = $offset; $index -le $end; ++$index) {
                '0x{0:x2}' -f $bytes[$index]
            }
            $lines.Add('    ' + ($values -join ', ') + ',')
        }
        $lines.Add('};')
        $lines.Add("inline constexpr unsigned int ${name}Size = sizeof($name);")
        return $lines
    }

    $generated = [Collections.Generic.List[string]]::new()
    $generated.Add('// Generated by tools/Compile-Fsr1Shaders.ps1 with Windows SDK 10.0.26100.0 FXC.')
    $generated.Add('// Source: SexyAppFramework/shaders/Fsr1Pass.hlsl; target: cs_5_0; full precision.')
    $generated.Add('#pragma once')
    $generated.Add('')
    $generated.Add('namespace Sexy')
    $generated.Add('{')
    $generated.Add('namespace Fsr1Shaders')
    $generated.Add('{')
    foreach ($line in (Format-ByteArray $easuPath 'gEasuCS')) { $generated.Add('    ' + $line) }
    $generated.Add('')
    foreach ($line in (Format-ByteArray $rcasPath 'gRcasCS')) { $generated.Add('    ' + $line) }
    $generated.Add('}')
    $generated.Add('}')
    $generatedText = ($generated -join "`n") + "`n"

    if ($Verify) {
        if (-not (Test-Path -LiteralPath $headerPath)) { throw "Missing generated header: $headerPath" }
        $existingText = [IO.File]::ReadAllText($headerPath)
        if ($existingText -ne $generatedText) { throw 'FSR shader bytecode is stale. Regenerate without -Verify.' }
    } else {
        [IO.File]::WriteAllText($headerPath, $generatedText, [Text.UTF8Encoding]::new($false))
    }
} finally {
    Remove-Item -LiteralPath $tempRoot -Recurse -Force
}
